PluginAndPartners/cart-magento2

composer.json, src/MercadoPago/Core/composer.json, src/MercadoPago/Core/etc/module.xml
=> CSRF / ML URLS

src/MercadoPago/Core/view/frontend/web/js/MPv1.js
[PLUG-790](https://mercadolibre.atlassian.net/browse/PLUG-790)
=> Fix MPv1.js for MLM

src/MercadoPago/Core/Helper/Data.php
[PPP-1105](https://mercadolibre.atlassian.net/browse/PPP-1105)
=> Add validation to payment_method_id and method on getAnalyticsData method

.gitignore, CHANGELOG.md, README.md, composer.json, src/MercadoPago/Core/Helper/Data.php, src/MercadoPago/Core/Model/CustomBankTransfer/Payment.php, src/MercadoPago/Core/composer.json, src/MercadoPago/Core/etc/adminhtml/system/basic_checkout.xml, src/MercadoPago/Core/etc/adminhtml/system/custom_checkout.xml, src/MercadoPago/Core/etc/module.xml, src/MercadoPago/Core/view/frontend/web/js/MPv1.js
=> Backport from master MP to P&P

src/MercadoPago/Core/Model/Core.php
https://mercadolibre.atlassian.net/browse/PLUG-953
=> Corrigido o arredondamento do transaction amount - bugfix/PLUG-953

src/MercadoPago/Core/view/frontend/web/js/MPv1.js
Add getBin on getIssers call...
=> Little adjusted

src/MercadoPago/Core/Plugin/OrderCancelPlugin.php
* Update OrderCancelPlugin.php
Corrigindo cancelamento de boleto.
* Update OrderCancelPlugin.php
"Encodando" body da requisição para cancelamento de pagamento.
=> Update OrderCancelPlugin.php (#155)

src/MercadoPago/Core/view/frontend/templates/custom_pix/success.phtml
=> Set BRL format to display amount on success page

src/MercadoPago/Core/Model/System/Message/CustomPixMessageNotification.php
=> clean config cache after notification

src/MercadoPago/Core/etc/config.xml, src/MercadoPago/Core/i18n/es_AR.csv, src/MercadoPago/Core/i18n/es_CL.csv, src/MercadoPago/Core/i18n/es_CO.csv, src/MercadoPago/Core/i18n/es_MX.csv, src/MercadoPago/Core/i18n/es_PE.csv, src/MercadoPago/Core/i18n/es_UY.csv, src/MercadoPago/Core/i18n/pt_BR.csv, src/MercadoPago/Core/view/frontend/requirejs-config.js, src/MercadoPago/Core/view/frontend/web/template/payment/custom_method.html, src/MercadoPago/Core/view/frontend/web/template/payment/custom_pix.html
=> fixed custom error messages and adjusted pix translate

src/MercadoPago/Core/Model/Core.php, src/MercadoPago/Core/Model/Preference/Basic.php, src/MercadoPago/Core/Model/Preference/Wallet.php
[https://mercadolibre.atlassian.net/browse/PLUG-1111](https://mercadolibre.atlassian.net/browse/PLUG-1111)
=> Added source_news to receive only one type of notification

src/MercadoPago/Core/view/frontend/web/js/view/method-renderer/custom-method.js
Correção do valor total apresentado nas parcelas do CHO Custom.
=> Corrected the total value of the installments shown in front

src/MercadoPago/Core/Helper/Data.php, src/MercadoPago/Core/Model/Notifications/Topics/Payment.php, src/MercadoPago/Core/Model/Notifications/Topics/TopicsAbstract.php
- Ajuste o placeholder de %s para %1 padrão do Magento
=> :bug: Set default Magento placeholder %1

src/MercadoPago/Core/Block/Adminhtml/System/Config/Fieldset/Payment.php, src/MercadoPago/Core/Helper/Message/AbstractMessage.php, src/MercadoPago/Core/Helper/Message/MessageInterface.php, src/MercadoPago/Core/Helper/Message/StatusDetailMessage.php, src/MercadoPago/Core/Helper/Message/StatusMessage.php, src/MercadoPago/Core/Helper/Message/StatusOrderMessage.php, src/MercadoPago/Core/Observer/ConfigObserver.php, src/MercadoPago/Core/etc/adminhtml/system.xml, src/MercadoPago/Core/etc/adminhtml/system/advanced.xml, src/MercadoPago/Core/etc/adminhtml/system/basic_checkout.xml, src/MercadoPago/Core/etc/adminhtml/system/custom_checkout.xml, src/MercadoPago/Core/etc/adminhtml/system/custom_checkout_bank_transfer.xml, src/MercadoPago/Core/etc/adminhtml/system/custom_checkout_pix.xml, src/MercadoPago/Core/etc/adminhtml/system/custom_checkout_ticket.xml, src/MercadoPago/Core/etc/adminhtml/system/custom_checkout_webpay.xml, src/MercadoPago/Core/etc/adminhtml/system/order_management.xml, src/MercadoPago/Core/etc/config.xml, src/MercadoPago/Core/i18n/es_AR.csv, src/MercadoPago/Core/i18n/es_CL.csv, src/MercadoPago/Core/i18n/es_CO.csv, src/MercadoPago/Core/i18n/es_MX.csv, src/MercadoPago/Core/i18n/es_PE.csv, src/MercadoPago/Core/i18n/es_UY.csv, src/MercadoPago/Core/i18n/pt_BR.csv
[https://mercadolibre.atlassian.net/browse/PPSM-86](https://mercadolibre.atlassian.net/browse/PPSM-86)
=> Added webpay gateway admin

src/MercadoPago/Core/Controller/CustomWebpay/AbstractAction.php, src/MercadoPago/Core/Controller/CustomWebpay/Reserve.php, src/MercadoPago/Core/Model/Custom/Payment.php, src/MercadoPago/Core/Model/CustomWebpay/Payment.php, src/MercadoPago/Core/Model/CustomWebpayConfigProvider.php, src/MercadoPago/Core/etc/di.xml, src/MercadoPago/Core/view/frontend/requirejs-config.js, src/MercadoPago/Core/view/frontend/web/js/view/method-renderer/custom-method-webpay.js, src/MercadoPago/Core/view/frontend/web/js/view/method-renderer/custom-method.js, src/MercadoPago/Core/view/frontend/web/template/payment/custom_webpay.html
[https://mercadolibre.atlassian.net/browse/PPSM-99](https://mercadolibre.atlassian.net/browse/PPSM-99)
=> Reserved cart id to create order on webpay callback

src/MercadoPago/Core/Model/CustomWebpay/Payment.php, src/MercadoPago/Core/Model/CustomWebpayConfigProvider.php, src/MercadoPago/Core/etc/di.xml, src/MercadoPago/Core/view/frontend/requirejs-config.js, src/MercadoPago/Core/view/frontend/web/js/view/method-renderer/custom-method-webpay.js, src/MercadoPago/Core/view/frontend/web/js/view/method-renderer/custom-method.js, src/MercadoPago/Core/view/frontend/web/template/payment/custom_webpay.html
[https://mercadolibre.atlassian.net/browse/PPSM-88](https://mercadolibre.atlassian.net/browse/PPSM-88)
=>  Implemented sdk v2 webpay tokenizer

src/MercadoPago/Core/Controller/CustomWebpay/Success.php, src/MercadoPago/Core/Helper/Data.php, src/MercadoPago/Core/Model/Core.php, src/MercadoPago/Core/Model/Custom/Payment.php, src/MercadoPago/Core/Model/CustomWebpay/Payment.php, src/MercadoPago/Core/Model/Preference/Wallet.php, src/MercadoPago/Core/i18n/es_AR.csv, src/MercadoPago/Core/i18n/es_CL.csv, src/MercadoPago/Core/i18n/es_CO.csv, src/MercadoPago/Core/i18n/es_MX.csv, src/MercadoPago/Core/i18n/es_PE.csv, src/MercadoPago/Core/i18n/es_UY.csv, src/MercadoPago/Core/i18n/pt_BR.csv
[https://mercadolibre.atlassian.net/browse/PPSM-89](https://mercadolibre.atlassian.net/browse/PPSM-89)
=> Create webpay callback

src/MercadoPago/Core/Block/CustomWebpay/Success.php, src/MercadoPago/Core/Controller/CustomWebpay/AbstractAction.php, src/MercadoPago/Core/Controller/CustomWebpay/Pay.php, src/MercadoPago/Core/Controller/CustomWebpay/Success.php, src/MercadoPago/Core/Model/CustomWebpay/Payment.php, src/MercadoPago/Core/view/frontend/layout/mercadopago_custom_webpay_success.xml
Link Jira: https://mercadolibre.atlassian.net/browse/PPSM-90
=> Add Success Page to Webpay

src/MercadoPago/Core/Block/AbstractSuccess.php, src/MercadoPago/Core/Block/Custom/Success.php, src/MercadoPago/Core/Block/CustomWebpay/Failure.php, src/MercadoPago/Core/Helper/Round.php, src/MercadoPago/Core/Model/Core.php, src/MercadoPago/Core/Model/Custom/Payment.php, src/MercadoPago/Core/Model/CustomTicket/Payment.php, src/MercadoPago/Core/Model/CustomWebpay/Payment.php, src/MercadoPago/Core/Model/Preference/Basic.php, src/MercadoPago/Core/Model/Preference/Wallet.php, src/MercadoPago/Core/i18n/es_AR.csv, src/MercadoPago/Core/i18n/es_CL.csv, src/MercadoPago/Core/i18n/es_CO.csv, src/MercadoPago/Core/i18n/es_MX.csv, src/MercadoPago/Core/i18n/es_PE.csv, src/MercadoPago/Core/i18n/es_UY.csv, src/MercadoPago/Core/i18n/pt_BR.csv, src/MercadoPago/Core/view/frontend/templates/basic/success.phtml, src/MercadoPago/Core/view/frontend/templates/custom/success.phtml, src/MercadoPago/Core/view/frontend/templates/custom_bank_transfer/success.phtml, src/MercadoPago/Core/view/frontend/web/js/CreditCard.js, src/MercadoPago/Core/view/frontend/web/js/view/method-renderer/custom-method.js, src/MercadoPago/Core/view/frontend/web/template/payment/custom_method.html
CHANGELOG:
- Added round helper to avoid fraud status on gateways
- Fixed custom-checkout.js to finish order
- Fixed retry order link and Added persistCartSession method to avoid cleaning cart on error
=> Added round helper to avoid fraud status

src/MercadoPago/Core/i18n/es_AR.csv, src/MercadoPago/Core/i18n/es_CL.csv, src/MercadoPago/Core/i18n/es_CO.csv, src/MercadoPago/Core/i18n/es_MX.csv, src/MercadoPago/Core/i18n/es_PE.csv, src/MercadoPago/Core/i18n/es_UY.csv, src/MercadoPago/Core/i18n/pt_BR.csv, src/MercadoPago/Core/view/frontend/templates/custom_pix/success.phtml
- add order ID to PIX congratulations page
- adds translations to PIX congrats page
=> add order id in congrats PIX page  [PPSM-154]

.github/workflows/main.yaml, bin/install-mg2.sh, src/MercadoPago/Test/coverage-checker.php
This pull request does:
- add colors to test command output
- adds pull request test coverage metric
=> Adds test coverage metric for Pull Request

src/MercadoPago/Core/Model/Notifications/Topics/Payment.php, src/MercadoPago/Core/Model/Notifications/Topics/TopicsAbstract.php
Coupon amount Mercado Pago incluído na verificação de status de fraude 
https://mercadolibre.atlassian.net/browse/PLUG-1385
=> Coupon amount Mercado Pago incluído na verificação de status de fraude - Fix/PLUG-1385

src/MercadoPago/Core/Model/Notifications/Topics/Payment.php, src/MercadoPago/Core/Model/Notifications/Topics/TopicsAbstract.php, src/MercadoPago/Core/view/frontend/web/template/payment/custom_method.html
* Fixed frontend typo;
* Fixed merge conflict;
=> [PPSM-339] Fixing CHO Pro Merge Conflicts

src/MercadoPago/Core/Helper/Round.php, src/MercadoPago/Test/Unit/Helper/RoundTest.php
Tivemos um GIN: https://mercadolibre.atlassian.net/browse/PLUG-1485
Com um problema no arredondamento para clientes Colombia e Chile para número inteiro.
=> Ajustado método de conversão de moeda

.editorconfig, Makefile, bin/run-linters.sh, bin/run-sync-files.sh
https://user-images.githubusercontent.com/1247740/141518364-ed7f6037-868a-4d70-b17a-923743fdc089.mov
Coloquei mais um comando para sincronizar os arquivos locais com o container com o Magento
=> feat(bin): ✨ new command sync with container

src/MercadoPago/Core/view/frontend/web/js/view/method-renderer/custom-method-bank-transfer.js
=> Hotfix: bank transfer js

src/MercadoPago/Core/Block/Adminhtml/System/Config/Fieldset/Payment.php, src/MercadoPago/Core/etc/config.xml
Removing "Debit Card" text from checkout custom.
Also fixing a minor bug on admin's Payment constructor.
=> Revert KLAP Text

CHANGELOG.md, README.md, composer.json, src/MercadoPago/Core/Block/Adminhtml/System/Config/Fieldset/Payment.php, src/MercadoPago/Core/composer.json, src/MercadoPago/Core/etc/module.xml
- Improvements to credit card flow
- Dynamically removing unavailable payment methods from admin
- Changed str_contains to srtpos
- Wallet Button working without CHO PRO enabled
=> Release v3.14.0 🚀

src/MercadoPago/Core/Model/Notifications/Topics/MerchantOrder.php, src/MercadoPago/Core/Model/Notifications/Topics/Payment.php, src/MercadoPago/Core/Model/Notifications/Topics/TopicsAbstract.php
Correção no email de confirmação de pedido para o status pendente. 
https://mercadolibre.atlassian.net/browse/PLUG-1724
=> Hotfix/PLUG-1724 - Fixed email creation for order confirmation in payment and merchant_order 

src/MercadoPago/Core/view/frontend/web/js/Masks.js, src/MercadoPago/Core/view/frontend/web/template/payment/custom_bank_transfer.html, src/MercadoPago/Core/view/frontend/web/template/payment/custom_method.html
Added new mask to avoid special characters in Document field.
=> Added new mask to avoid special characters in Document field

src/MercadoPago/Core/view/frontend/templates/custom_pix/success.phtml, src/MercadoPago/Core/view/frontend/web/css/style-success.css
New Pix Screen - Mobile Experience
**>Web**
**> Mobile**
**>Web**
**> Mobile**
=> New Pix Screen Mobile Experience

src/MercadoPago/Core/view/frontend/requirejs-config.js, src/MercadoPago/Core/view/frontend/web/js/CreditCard.js, src/MercadoPago/Core/view/frontend/web/js/UpdateCardForm.js, src/MercadoPago/Core/view/frontend/web/js/view/method-renderer/custom-method.js
To solve the bug, the following was done: As the cardForm doesn't have a method to update the received value, the only way to update its value is to recreate it (through the mount and unmount methods)
for this it was made
- CardForm initialization moved from custom-method.js file to CreditCard.js to have better control over cardForm mounting and unmounting
- UpdateCardForm.js  was created which mixin the function to unmount the cardForm with the function to apply and cancel the coupon coming from Magento/discount.js
=> [PPWP-1090] - Fix Discount Coupon 

composer.json, src/MercadoPago/Core/Block/Adminhtml/System/Config/InterestPayment/Button.php, src/MercadoPago/Core/Block/Adminhtml/System/Config/InterestPayment/Note.php, src/MercadoPago/Core/Helper/Data.php, src/MercadoPago/Core/Model/BasicConfigProvider.php, src/MercadoPago/Core/Model/Core.php, src/MercadoPago/Core/Model/CustomBankTransfer/Payment.php, src/MercadoPago/Core/Model/CustomTicket/Payment.php, src/MercadoPago/Core/Model/Preference/Basic.php, src/MercadoPago/Core/Model/Preference/Wallet.php
Ajustadas chamadas de funções que estavam quebrando no Magento 2.4.4 (PHP 8.1)
=> fix: 🐛 PPWP-1188 support php 8.1

CHANGELOG.md, README.md, composer.json, src/MercadoPago/Core/Block/Adminhtml/System/Config/InterestPayment/Button.php, src/MercadoPago/Core/Block/Adminhtml/System/Config/InterestPayment/Note.php, src/MercadoPago/Core/Helper/Data.php, src/MercadoPago/Core/Lib/RestClient.php, src/MercadoPago/Core/Model/BasicConfigProvider.php, src/MercadoPago/Core/Model/Core.php, src/MercadoPago/Core/Model/CustomBankTransfer/Payment.php, src/MercadoPago/Core/Model/CustomTicket/Payment.php, src/MercadoPago/Core/Model/Preference/Basic.php, src/MercadoPago/Core/Model/Preference/Wallet.php, src/MercadoPago/Core/composer.json, src/MercadoPago/Core/etc/module.xml, src/MercadoPago/Core/view/frontend/requirejs-config.js, src/MercadoPago/Core/view/frontend/templates/custom_pix/success.phtml, src/MercadoPago/Core/view/frontend/web/css/style-success.css, src/MercadoPago/Core/view/frontend/web/js/CreditCard.js, src/MercadoPago/Core/view/frontend/web/js/Masks.js, src/MercadoPago/Core/view/frontend/web/js/UpdateCardForm.js, src/MercadoPago/Core/view/frontend/web/js/view/method-renderer/custom-method.js, src/MercadoPago/Core/view/frontend/web/template/payment/custom_bank_transfer.html, src/MercadoPago/Core/view/frontend/web/template/payment/custom_method.html
* Added new mask to avoid special characters in Document field
* fix: removed sponsor id from header (#233)
* feat: initial structure
* New Pix Screen Mobile Experience
* feat(PPWP-1090): added event to call initCardForm
* fix: :bug: Fix bug when buyer applies a discount
* fix: :bug: Fix placeOrder context exec
* fix: 🐛 PPWP-1188 support php 8.1
* fix: 🐛 PPWP-1188 add require ext-mbstring
* build(v3.17.0): 📦 New version v3.17.0 of Mercado Pago for Magento 2
Co-authored-by: Cleiton Aguiar Andrade <cleiton.andrade@mercadolivre.com>
Co-authored-by: hugodamm <hugo2008rj@hotmail.com>
Co-authored-by: Giovanni Cavallari <giovanni.cavallari@mercadolivre.com>
Co-authored-by: sleaof <stephanie.leao@mercadolivre.com>
Co-authored-by: Hugo Damm <hugo.damm@mercadolivre.com>
Co-authored-by: …
=> Release/magento 3.17.0 (#194)
